In [2]:
import pandas as pd
print(pd.__version__)

2.3.3

In [7]:
import os
os.listdir()

['.config',
 'Music',
 'Untitled5.ipynb',
 'Untitled1.ipynb',
 '.DS_Store',
 '.CFUserTextEncoding',
 '.xonshrc',
 'Untitled3.ipynb',
 'Untitled.ipynb',
 '.zshrc',
 'Untitled4.ipynb',
 'Pictures',
 '.zprofile',
 'Untitled2.ipynb',
 '.ipython',
 'Desktop',
 'Library',
 'Public',
 '.tcshrc',
 '.anaconda',
 'Movies',
 '.Trash',
 '.ipynb_checkpoints',
 '.jupyter',
 'Documents',
 '.bash_profile',
 'sales_data_csv',
 'Downloads',
 '.zsh_sessions',
 '.conda']

In [8]:
import os
print(os.getcwd())
print(os.listdir())

/Users/markay
['.config', 'Music', 'Untitled5.ipynb', 'Untitled1.ipynb', '.DS_Store', '.CFUserTextEncoding', '.xonshrc', 'Untitled3.ipynb', 'Untitled.ipynb', '.zshrc', 'Untitled4.ipynb', 'Pictures', '.zprofile', 'Untitled2.ipynb', '.ipython', 'Desktop', 'Library', 'Public', '.tcshrc', '.anaconda', 'Movies', '.Trash', '.ipynb_checkpoints', '.jupyter', 'Documents', '.bash_profile', 'sales_data_csv', 'Downloads', '.zsh_sessions', '.conda']

In [9]:
import pandas as pd
data = pd.read_csv("/Users/markay/sales_data_csv")
data

         Date     Product  Quantity  Price
0  2026-01-01       Phone         2    300
1  2026-01-02      Laptop         1    800
2  2026-01-03  Headphones         3     50
3  2026-01-04       Phone         1    300
4  2026-01-05      Laptop         2    800
5  2026-01-06       Mouse         5     20
6  2026-01-07    Keyboard         2     40

In [10]:
##Add total coulumn###
data["Total"] = data["Quantity"] * data["Price"]
data

         Date     Product  Quantity  Price  Total
0  2026-01-01       Phone         2    300    600
1  2026-01-02      Laptop         1    800    800
2  2026-01-03  Headphones         3     50    150
3  2026-01-04       Phone         1    300    300
4  2026-01-05      Laptop         2    800   1600
5  2026-01-06       Mouse         5     20    100
6  2026-01-07    Keyboard         2     40     80

In [11]:
##Total sales###
data["Total"].sum

<bound method Series.sum of 0     600
1     800
2     150
3     300
4    1600
5     100
6      80
Name: Total, dtype: int64>

In [12]:
##Best selling product##
data.groupby("Product")["Total"].sum().idxmax()

'Laptop'

In [14]:
##Sales by product##
data.groupby("Product")["Total"].sum()

Product
Headphones     150
Keyboard        80
Laptop        2400
Mouse          100
Phone          900
Name: Total, dtype: int64